// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ass1_ef__core.DatabseContext;

#nullable disable

namespace ass1_ef__core.Migrations
{
    [DbContext(typeof(AirlineDbContext))]
    [Migration("20251203220403_AddAirCraftRouteTable")]
    partial class AddAirCraftRouteTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ass1_ef__core.airlineModels.AirCraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("airlineid")
                        .HasColumnType("int");

                    b.Property<string>("assistant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<string>("host1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("host2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maj_pilot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("airlineid");

                    b.ToTable("AirCrafts");
                });

            modelBuilder.Entity("ass1_ef__core.airlineModels.AirCraftRoute", b =>
                {
                    b.Property<int>("AirCraftId")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AirCraftId", "RouteId");

                    b.HasIndex("RouteId");

                    b.ToTable("AirCraftRoute");
                });

            modelBuilder.Entity("ass1_ef__core.airlineModels.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("ass1_ef__core.airlineModels.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("al_id")
                        .HasColumnType("int");

                    b.Property<int>("db_day")
                        .HasColumnType("int");

                    b.Property<int>("db_month")
                        .HasColumnType("int");

                    b.Property<int>("db_year")
                        .HasColumnType("int");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("AirlineId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ass1_ef__core.airlineModels.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("ass1_ef__core.airlineModels.Route", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("distance")
                        .HasColumnType("int");

                    b.Property<string>("origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("ass1_ef__core.airlineModels.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("airlinid")
                        .HasColumnType("int");

                    b.Property<int>("al_id")
                        .HasColumnType("int");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("airlinid");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ass1_ef__core.airlineModels.AirCraft", b =>
                {
                    b.HasOne("ass1_ef__core.airlineModels.Airline", "airCraftLine")
                        .WithMany("aircrafts")
                        .HasForeignKey("airlineid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ass1_ef__core.airlineModels.Crew", "crew", b1 =>
                        {
                            b1.Property<int>("AirCraftId")
                                .HasColumnType("int");

                            b1.Property<string>("assis_pilot")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("host1")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("host2")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("maj_pilot")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AirCraftId");

                            b1.ToTable("AirCrafts");

                            b1.WithOwner()
                                .HasForeignKey("AirCraftId");
                        });

                    b.Navigation("airCraftLine");

                    b.Navigation("crew");
                });

            modelBuilder.Entity("ass1_ef__core.airlineModels.AirCraftRoute", b =>
                {
                    b.HasOne("ass1_ef__core.airlineModels.AirCraft", "AirCraft")
                        .WithMany("AirCraftRoutes")
                        .HasForeignKey("AirCraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ass1_ef__core.airlineModels.Route", "Route")
                        .WithMany("AirCraftRoutes")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirCraft");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("ass1_ef__core.airlineModels.Employee", b =>
                {
                    b.HasOne("ass1_ef__core.airlineModels.Airline", "airline")
                        .WithMany("employees")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("airline");
                });

            modelBuilder.Entity("ass1_ef__core.airlineModels.Phone", b =>
                {
                    b.HasOne("ass1_ef__core.airlineModels.Airline", "Airline")
                        .WithMany("Phones")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("ass1_ef__core.airlineModels.Transaction", b =>
                {
                    b.HasOne("ass1_ef__core.airlineModels.Airline", "airlinetransaction")
                        .WithMany("transactions")
                        .HasForeignKey("airlinid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("airlinetransaction");
                });

            modelBuilder.Entity("ass1_ef__core.airlineModels.AirCraft", b =>
                {
                    b.Navigation("AirCraftRoutes");
                });

            modelBuilder.Entity("ass1_ef__core.airlineModels.Airline", b =>
                {
                    b.Navigation("Phones");

                    b.Navigation("aircrafts");

                    b.Navigation("employees");

                    b.Navigation("transactions");
                });

            modelBuilder.Entity("ass1_ef__core.airlineModels.Route", b =>
                {
                    b.Navigation("AirCraftRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
